Made pod check simpler

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -1,7 +1,13 @@
-#!/bin/sh
-set -e
-./minislate build
-./minislate init
+#!/bin/bash
+cd $(dirname $0)/..
 echo
 printf "ALL PODS UP: "
-./minislate kubectl get pods -n kube-system | awk '{print $1 "," $3}' | test/pods_test || ./minislate kubectl get pods -n kube-system
+pods=$(./minislate kubectl get pods -n kube-system | tail -n +2)
+while read -r line; do
+	status=$(echo "$line" | awk '{print $3}')
+	if [ "$status" != "Running" ]; then
+		echo "FAIL"
+		exit 1
+	fi
+done <<< "$pods"
+echo "PASS"
